# Utilisez une image Node.js en tant qu'image de base
FROM node:14

# Créez le répertoire de travail de l'application
WORKDIR /usr/src/app

# Copiez le package.json et le package-lock.json pour installer les dépendances
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste de l'application
COPY . .

# Exposez le port sur lequel votre application s'exécute
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["node", "app.js"]