# Utiliser une image de base avec PHP et Apache
FROM php:7.4-apache

# Copier les fichiers de l'application dans le conteneur
COPY index.php /var/www/html/
COPY home.php /var/www/html/

# Exposer le port 80 pour permettre l'accès au serveur web
EXPOSE 80
